services:
  namik-ddns:
    build:
      context: ../
      dockerfile: ./docker/namik-ddns/Dockerfile
    container_name: namik-ddns
    environment:
      NODE_ENV: production
      PORT: 4321
      BASE_DOMAIN: example.com
      NAMESERVERS: ns.example2.com
    ports:
      - "4321:4321"
    restart: always
    networks:
      - pdns-network
    volumes:
      - prod_db_data:/namik-ddns/data

  powerdns:
    build:
      context: ./powerdns
      dockerfile: Dockerfile
    container_name: powerdns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - pdns-network
    restart: always
    depends_on:
      - namik-ddns

  caddy:
    image: caddy:latest
    container_name: caddy
    environment:
      EMAIL: example@email.com
      BASE_DOMAIN: example.com
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - namik-ddns
    networks:
      - pdns-network
    restart: always

networks:
  pdns-network:
    driver: bridge

volumes:
  prod_db_data:
  caddy_data:
  caddy_config:
